### ISSUE TITLE
"No relations found" warning for bootstrap

### ISSUE THREAD

**Issue by foundinblank** [mikekaminsky/dbt-helper#18] opened 2019-04-30 14:43 UTC
Love this package! When I run `dbt-helper bootstrap --schemas user_phone_directory`, I get `Warning: No relations found in selected schemas: ['user_phone_directory']. Aborting.`

A few questions: 
1. Could this be related to homebrew vs. pip? I installed dbt via homebrew. 
2. I'm not sure how the --schemas flag works, is it to refer to a specific model name (aka, the --model flag), or a whole folder? 
3. No relations, why?

**Comment by mikekaminsky** [comment] 2019-04-30 14:59
@foundinblank great questions! 

1. Could be! Though I'm surprised this works at all if that was the root issue. Can you try this again in a fresh virtual environment with both `dbt` and `dbt-helper` installed via pip?
2. the `--schema` flag references a schema _in the database_. So `dbt-helper` is assuming that `user_phone_directory` is the name of a schema in your warehouse.
3. Are there relations in the `user_phone_directory` schema in your warehouse?

I think the issue is probably with #2 here, but let me know if not!

**Comment by foundinblank** [comment] 2019-04-30 15:12
Thanks for the quick response, @mikekaminsky! 

1. "A fresh virtual environment" - not sure how to set this up and afraid to mess around with my existing dbt installation. Where do I start (if this is worth trying...it does seem to be working after all)? 

2. A schema in the database. Okay, so I use Snowflake, and my analytics schema (officially ANALYTICS.ANALYTICS) has 70 tables/views in it. So I am bootstrapping all of these? I also know Snowflake has weird uppercase and quoting rules, so I tried all of the below: 
- analytics
- analytics.analytics
- ANALYTICS
- ANALYTICS.ANALYTICS
- "ANALYTICS"
- 'ANALYTICS'
- "ANALYTICS.ANALYTICS"
- 'ANALYTICS.ANALYTICS'
- "ANALYTICS"."ANALYTICS"
- 'ANALYTICS'.'ANALYTICS'

3. No relations in my user_phone_directory view (I think). What do you mean by relations? It has ref() calls to upstream models, and there are downstream models that pull from it.

**Comment by mikekaminsky** [comment] 2019-04-30 15:15
@foundinblank got it! So `dbt-helper bootstrap` only cares about the schemas in the warehouse, not the "folders" on your computer.

If you run `dbt-helper bootstrap --schemas analytics` then dbt-helper will look at all of the relations in that schema and will print out starter `schema.yml` templates for them

**Comment by mikekaminsky** [comment] 2019-04-30 15:27
Now that I'm re-reading your message, maybe you already tried this? If so, I'm not sure how to fix! I don't have access to a snowflake warehouse to test, unfortunately :/

**Comment by mikekaminsky** [comment] 2019-04-30 18:19
I'm going to close this issue in favor of https://github.com/mikekaminsky/dbt-helper/issues/19 which more clearly specifies the problem. If you have more ideas for what to do here, please pop them on that issue :)

**Closed by mikekaminsky** 2019-04-30 18:19 UTC

**Comment by foundinblank** [comment] 2019-05-01 10:12
Gotcha, okay!
